### ISSUE TITLE
Remove "Lorem ipsum..."

### ISSUE THREAD

**Issue by eljhkrr** [hackrush/hackrush.github.io#1]

**Comment by rawteech** [comment]
No problem @TheRakken Still working on the contents. The updates will be pushed soon

**Comment by eljhkrr** [comment]
:+1:

**Comment by rawteech** [comment]
Lorem ipsum removed and content added... hope all is well

**Comment by eljhkrr** [comment]
Cool man! 
Now close this issue because you've sorted it out.

**Comment by rawteech** [comment]
Yep sure thanks...
