### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by roboflank** [hackrush/hackrush.github.io#5]
@rawteech  Can you attach the logo here?

**Comment by rawteech** [comment]
@denzelwamburu Yep, working on that. It will be up soon :boom:

**Comment by rawteech** [comment]
@denzelwamburu still having issues adding the logo. It works in the local repo, but doesn't seem to load on the online page
![local repo](https://cloud.githubusercontent.com/assets/5724682/16358081/673fab4c-3b11-11e6-9f25-dc78129bd947.PNG)

**Comment by roboflank** [comment]
Fixed https://github.com/hackrush/hackrush.github.io/pull/10
