### ISSUE TITLE
long loading time

### ISSUE THREAD

**Issue by turuthivic** [hackrush/hackrush.github.io#8]
landing page taking a huge load of time to fire up

**Comment by roboflank** [comment]
@turuthivic  Noted.
I think the images are too large/heavy

**Comment by roboflank** [comment]
@rawteech  Maybe you can find a way of optimizing the images.

**Comment by rawteech** [comment]
Yeah, also noted the issue, will scale down the images to web format

**Comment by roboflank** [comment]
@rawteech https://github.com/hackrush/hackrush.github.io/commit/8f19655dd6b5cf9e1e864dc54ded30e65f28fe0e Seems to have fixed this. :+1:  
It seems great from my side. @turuthivic

**Comment by turuthivic** [comment]
yeah..awesome work on that @rawteech
